arb-dir: lib/l10n
<<<<<<< HEAD
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart

=======
output-dir: lib/generated
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
>>>>>>> hyacinthe
